language: node_js
node_js:
- node
- lts/*
- 6

env:
  matrix:
    - PACKAGE = ci-info
    - PACKAGE = is-ci
    - PACKAGE = is-pr

branches:
  only:
  - master

install:
  - npm install

script: 
  - lerna run test --scope $PACKAGE
