language: node_js
node_js:
- '10'
- '8'
- '6'

env:
  matrix:
    - PACKAGE = ci-info
    - PACKAGE = is-ci
    - PACKAGE = is-pr

branches:
  only:
  - master

install:
  - yarn

script: 
  - lerna run test --scope $PACKAGE
